/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p47.reto5.vista;

import javax.swing.JOptionPane;
import utp.misiontic2022.c2.p47.reto5.controlador.ControladorRequerimientos;


/**
 *
 * @author SANTIAGO
 */
public class VistaRequerimientoGUI extends javax.swing.JFrame {

    private ControladorRequerimientos controlador;
    private Consulta1TM consulta1TM;
    private Consulta2TM consulta2TM;
    private Consulta3TM consulta3TM;
    
    public VistaRequerimientoGUI() {
        controlador = new ControladorRequerimientos();
        initComponents();
        listarConsulta1();
        listarConsulta2();
        listarConsulta3();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        Consulta1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Consulta2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Consulta3 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        miMenu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mVentanas = new javax.swing.JMenu();
        miConsulta1 = new javax.swing.JMenuItem();
        miConsulta2 = new javax.swing.JMenuItem();
        miConsulta3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));

        Consulta1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(30, 130));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de Consulta");
        jPanel3.add(jLabel1);

        jSplitPane1.setLeftComponent(jPanel3);

        Consulta1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Constulta 1", Consulta1);

        Consulta2.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setEnabled(false);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel4);

        jLabel2.setText("Gestion de Consulta");
        jPanel6.add(jLabel2);

        jSplitPane2.setLeftComponent(jPanel6);

        Consulta2.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Consulta 2", Consulta2);

        Consulta3.setLayout(new java.awt.BorderLayout());

        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setEnabled(false);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel10.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jSplitPane3.setRightComponent(jPanel10);

        jLabel4.setText("Gestion de Consulta");
        jPanel12.add(jLabel4);

        jSplitPane3.setLeftComponent(jPanel12);

        Consulta3.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Consulta 3", Consulta3);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.CENTER);

        miMenu.setMinimumSize(new java.awt.Dimension(100, 22));

        mArchivo.setText("Archivo");

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mArchivo.add(mSalir);

        miMenu.add(mArchivo);

        mVentanas.setText("Ventanas");

        miConsulta1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miConsulta1.setText("Consulta 1");
        miConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsulta1ActionPerformed(evt);
            }
        });
        mVentanas.add(miConsulta1);

        miConsulta2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miConsulta2.setText("Consulta 2");
        miConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsulta2ActionPerformed(evt);
            }
        });
        mVentanas.add(miConsulta2);

        miConsulta3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miConsulta3.setText("Consulta 3");
        miConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsulta3ActionPerformed(evt);
            }
        });
        mVentanas.add(miConsulta3);

        miMenu.add(mVentanas);

        setJMenuBar(miMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsulta2ActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_miConsulta2ActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
         if (JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicacion",getTitle(),JOptionPane.YES_OPTION)== JOptionPane.YES_OPTION) {
             dispose();
        }
    }//GEN-LAST:event_mSalirActionPerformed

    private void miConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsulta1ActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_miConsulta1ActionPerformed

    private void miConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsulta3ActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_miConsulta3ActionPerformed

    
    private void listarConsulta1(){
        try {
            var registrosBS = controlador.consultarRequerimiento1();
             consulta1TM = new Consulta1TM(registrosBS);
             jTable1.setModel(consulta1TM);
        } catch (Exception e) {
        }
    }
    
    private void listarConsulta2(){
        try {
            var registrosBS2 = controlador.consultarRequerimiento2();
            consulta2TM = new Consulta2TM(registrosBS2);
            jTable2.setModel(consulta2TM);
        } catch (Exception e) {
        }
    }
    private void listarConsulta3(){
        try {
            var registrosBS3 = controlador.consultarRequerimiento3();
            consulta3TM = new Consulta3TM(registrosBS3);
            jTable4.setModel(consulta3TM);
        } catch (Exception e) {
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Consulta1;
    private javax.swing.JPanel Consulta2;
    private javax.swing.JPanel Consulta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenu mVentanas;
    private javax.swing.JMenuItem miConsulta1;
    private javax.swing.JMenuItem miConsulta2;
    private javax.swing.JMenuItem miConsulta3;
    private javax.swing.JMenuBar miMenu;
    private javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables
}
